apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deployment
   labels:
     app: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
       app: nginx-deploy
  template:
    metadata:
      labels:
      app: nginx-deploy
    spec:
      containers:
        - name: nginx
          image: nginx:1.12
          ports:
           - containerPort: 80
      affinity:
        nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 1
             preference:
               matchExpressions:
               - key: disktype
                 operator: In # if operator was (NOtIn) it is anti-node affinity
                 values:
                 - ssd