apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod
   labels:
     app: mypod
spec:
  containers:
     - name: nginx-cont
       image: stacksimplify/kubenginx:1.0.0
       ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    app: mypod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80